In [3]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
data = pd.read_csv('https://raw.githubusercontent.com/kdemertzis/EKPA/main/Data/phishing_dataset.csv', delimiter=',')

In [4]:
data = data.sample(frac=1).reset_index(drop=True)
data.head()

Domain  Have_IP  Have_At  URL_Length  URL_Depth  \
0  clienteappsms-com.umbler.net        0        0           0          1   
1   bbcorretoradeseguros.com.br        0        0           0          0   
2                       9gag.tv        0        0           1          3   
3                thenextweb.com        0        0           1          6   
4              gooyatoronto.com        0        0           0          0   

   Redirection  https_Domain  TinyURL  Prefix/Suffix  DNS_Record  Web_Traffic  \
0            0             0        0              1           0            0   
1            0             0        0              0           0            1   
2            0             0        0              0           0            0   
3            0             0        0              0           0            1   
4            0             0        0              0           0            0   

   Domain_Age  Domain_End  iFrame  Mouse_Over  Right_Click  Web_Forwards  \
0           0           1       1           1            1             1   
1           1           1       0           0            1             0   
2           0           0       0           0            1             0   
3           0           0       0           0            1             0   
4           0           0       0           0            1             0   

   Label  
0      1  
1      1  
2      0  
3      0  
4      1

In [5]:
X = data.drop(['Domain', 'Label'], axis=1)

In [6]:
X.head()

Have_IP  Have_At  URL_Length  URL_Depth  Redirection  https_Domain  \
0        0        0           0          1            0             0   
1        0        0           0          0            0             0   
2        0        0           1          3            0             0   
3        0        0           1          6            0             0   
4        0        0           0          0            0             0   

   TinyURL  Prefix/Suffix  DNS_Record  Web_Traffic  Domain_Age  Domain_End  \
0        0              1           0            0           0           1   
1        0              0           0            1           1           1   
2        0              0           0            0           0           0   
3        0              0           0            1           0           0   
4        0              0           0            0           0           0   

   iFrame  Mouse_Over  Right_Click  Web_Forwards  
0       1           1            1             1  
1       0           0            1             0  
2       0           0            1             0  
3       0           0            1             0  
4       0           0            1             0

In [7]:
#y=np.ravel(data['Label'])
y=np.ravel(data['Label'])

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state=43)

In [9]:
# Standardize the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [10]:
# Define classifiers
classifiers = [
    LogisticRegression(),
    SVC(),
    RandomForestClassifier(),
    MLPClassifier(),
    KNeighborsClassifier(),
    DecisionTreeClassifier()
]

In [11]:
# Evaluate and compare classifiers
results = {'Classifier': [], 'Accuracy': [], 'Precision': [], 'Recall': [], 'F1 Score': []}

for clf in classifiers:
    clf_name = clf.__class__.__name__

    # Train the classifier
    clf.fit(X_train, y_train)

    # Make predictions
    y_pred = clf.predict(X_test)

    # Calculate evaluation metrics
    acc = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='weighted')
    recall = recall_score(y_test, y_pred, average='weighted')
    f1 = f1_score(y_test, y_pred, average='weighted')

    # Confusion matrix
    cm = confusion_matrix(y_test, y_pred)

    # Display results
    print(f"\n{clf_name} Metrics:")
    print(f"Accuracy: {acc}")
    print(f"Precision: {precision}")
    print(f"Recall: {recall}")
    print(f"F1 Score: {f1}")
    print("Confusion Matrix:")
    print(cm)

    # Store results for comparison
    results['Classifier'].append(clf_name)
    results['Accuracy'].append(acc)
    results['Precision'].append(precision)
    results['Recall'].append(recall)
    results['F1 Score'].append(f1)


LogisticRegression Metrics:
Accuracy: 0.809
Precision: 0.8317101199400301
Recall: 0.809
F1 Score: 0.8065620567178922
Confusion Matrix:
[[1362   95]
 [ 478 1065]]

SVC Metrics:
Accuracy: 0.8346666666666667
Precision: 0.8629264839942871
Recall: 0.8346666666666667
F1 Score: 0.8321698216255269
Confusion Matrix:
[[1415   42]
 [ 454 1089]]

RandomForestClassifier Metrics:
Accuracy: 0.8653333333333333
Precision: 0.8728425219102071
Recall: 0.8653333333333333
F1 Score: 0.8649628561253562
Confusion Matrix:
[[1358   99]
 [ 305 1238]]


/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(



MLPClassifier Metrics:
Accuracy: 0.845
Precision: 0.849373569221084
Recall: 0.845
F1 Score: 0.8447999832345173
Confusion Matrix:
[[1304  153]
 [ 312 1231]]

KNeighborsClassifier Metrics:
Accuracy: 0.8406666666666667
Precision: 0.8482128587220565
Recall: 0.8406666666666667
F1 Score: 0.8401929296612558
Confusion Matrix:
[[1324  133]
 [ 345 1198]]

DecisionTreeClassifier Metrics:
Accuracy: 0.866
Precision: 0.8742522982373085
Recall: 0.866
F1 Score: 0.8655811334617226
Confusion Matrix:
[[1364   93]
 [ 309 1234]]


In [12]:
# Display comparison results
results_df = pd.DataFrame(results)
results_df = results_df.sort_values(by='Accuracy', ascending=False)
print("\nComparison of Classifiers:")
print(results_df)


Comparison of Classifiers:
               Classifier  Accuracy  Precision    Recall  F1 Score
5  DecisionTreeClassifier  0.866000   0.874252  0.866000  0.865581
2  RandomForestClassifier  0.865333   0.872843  0.865333  0.864963
3           MLPClassifier  0.845000   0.849374  0.845000  0.844800
4    KNeighborsClassifier  0.840667   0.848213  0.840667  0.840193
1                     SVC  0.834667   0.862926  0.834667  0.832170
0      LogisticRegression  0.809000   0.831710  0.809000  0.806562
